name: Test Angular App

on:
  pull_request:
    branches: [ main ]

jobs:
  build-angular:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node Js
        uses: actions/setup-node@v5
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm install

      - name: EsLint
        run: npm run eslint

      - name: Build
        run:  npm run build -- --base-href /MadzAngularWebsiteDeploymentTest/
        
    
